### ISSUE TITLE
Allow TLS settings for Consul client

### ISSUE THREAD

**Issue by Mo-Morris** [edgexfoundry/go-mod-registry#133]
**version:** edgex:3.0.0
I analyzer the sorce code when i config https. find the bug。

check consul client is alive when register to consul，source code blew：
internal/pkg/consul/client.go#L82
```
func (client *consulClient) IsAlive() bool {
	netClient := http.Client{Timeout: time.Second * 10}

	// This REST endpoint doesn't require Access Token, so no need to handle Auth Error.
	resp, err := netClient.Get(client.consulUrl + consulStatusPath)
	if err != nil {
		return false
	}

	if resp.StatusCode >= http.StatusOK && resp.StatusCode < http.StatusMultipleChoices {
		return true
	}

	return false
}
```
this always use http to check，so https client not to use！

**Comment by lenny-intel** [comment]
@Mo-Morris , this code is fine. It will use the protocol contained in`client.consulUrl`
But, EdgeX doesn't support configuring HTTP for this.
Here are is the configuration, which doesn't have Protocol.
https://github.com/edgexfoundry/edgex-go/blob/napa/cmd/core-common-config-bootstrapper/res/configuration.yaml#L39-L42

**Comment by cloudxxx8** [comment]
it's not a bug, but a feature ehancement request.
we currently don't provide option to set the ca cert or skip verify.
Please feel free to open a PR for this feature, and we will help review it.

**Comment by cloudxxx8** [comment]
Since the license change of Consul, we won't maintain its support in the future release.

**Comment by Mo-Morris** [comment]
您发的邮件我已收到，并会尽快处理，谢谢！
