### ISSUE TITLE
Suggestion: use status/leader rather than agent/self

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-registry#14]
...when checking whether consul is alive. agent/self returns >10K of description.

**Comment by lenny-intel** [comment]
@iain-anderson , sounds like a good change.  Note that this API is only called during boot-strap of the services so I consider this a low priority.
https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/data/init.go#L231

**Comment by iain-anderson** [comment]
Agreed

**Comment by michaelestrin** [comment]
Closed for inactivity.  Not sure if this is still an issue after common bootstrap changes (and subsequent extraction to go-mod-bootstrap).

**Comment by lenny-intel** [comment]
This applies to the URL that is used for the IsAlive() check. So it still applies and should be done as part of the refectoring.

**Comment by lenny-intel** [comment]
Addressing this in the Registry refactoring. It is a simple change in the REST path used.
