### ISSUE TITLE
Question: Why does this repo have Dockerfiles?

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-registry#17]
??

It really shouldn't since these aren't published as images. The repo itself is consumed as a dependency in other applications via Go modules.

**Comment by michaelestrin** [comment]
Looks as if the dockerfile is needed for the CI/CD process.  @lranjbar -- can you confirm and elaborate?

**Comment by lranjbar** [comment]
We build the services in docker and run the tests to control the environment in the CI process. The module repos were our first guinea pigs for this process. We have created documentation to explain this - it was presented at the Geneva F2F.

https://github.com/edgexfoundry/jenkins_pipeline_presentation#new-ci-requirements
