### ISSUE TITLE
Support Unregister func from Registry

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-registry#20]
Since there is a Register func in registry.Client interface, it should also support Unregister to remove the service from the registry

Here is a related issue
https://github.com/edgexfoundry/device-sdk-go/issues/217

**Comment by tsconn23** [comment]
It appears this has already been done
https://github.com/edgexfoundry/go-mod-registry/blob/1046cccd4841a3fd011f4d5cde55378f39b67fd6/registry/interface.go#L27

https://github.com/edgexfoundry/go-mod-registry/blob/1046cccd4841a3fd011f4d5cde55378f39b67fd6/internal/pkg/consul/client.go#L123

**Comment by lenny-intel** [comment]
@tsconn23 , correct. PR #38 addressed this. Closing
