### ISSUE TITLE
Tests should run cleanly when passed the -race option

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/go-mod-registry#35]
To ensure our tests (and to some extent production code) are reliable, we should be running unit tests with the -race argument in the Makefile. Currently, the tests fail when run in this mode.

Failing tests: 
* TestRegisterWithPingCallback() in internal/pkg/consul/client_test.go
* TestIsServiceAvailableNotHealthy() in internal/pkg/consul/client_test.go
* TestConfigurationValueExists() in internal/pkg/consul/client_test.go
* TestPutConfiguration() in internal/pkg/consul/client_test.go
* TestWatchForChanges() in internal/pkg/consul/client_test.go

This test should succeed when passed -race, and then we should add -race to the test target in our Makefile.

**Comment by brandonforster** [comment]
Per discussion on DevOps WG call on 27 February, this has been rescoped from Geneva to Hanoi so that DevOps can address some underlying build concerns.

**Comment by tsconn23** [comment]
After some local testing, it appears the tests called out in the original issue are now passing. I will create a PR that incorporates the `race` flag into the Makefile so that this condition is always on and then see how the CI/CD pipeline handles it.

**Comment by tsconn23** [comment]
See comment on PR #48 above. While the initial tests called out in the issue are no longer a problem, enabling the `-race` flag cannot be done until the project adopts Go 1.15

**Comment by jpwhitemn** [comment]
DevOps addressed
