### ISSUE TITLE
Custom Health Check Registration

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/go-mod-registry#64]
I have a branch going that allows us to register custom health checks with consul through the edgex RegistryClient and wanted to see if this would be of interest as a PR.  It was easy enough to register with consul directly but we're finding it keeps things a little neater.  

I still need to work out the tests, and once I can do that I may add the ability to deregister, although I don't see us needing that here.  I'll be rebasing to get in line with the 1.3.0 app sdk release soon and I don't think this would be a ton more work to get done and send back as a PR if it seems like useful functionality to expose. I'd always prefer not having to keep a fork up to date :)

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/go-mod-registry/pull/65
