### ISSUE TITLE
[suggestion]Add one new method return all register endpoint services

### ISSUE THREAD

**Issue by badboy-huaqiao** [edgexfoundry/go-mod-registry#77]
I think there should be one method to return all register services, then UI or system agent can get all services user started by call this new method.

Users also can directly call the api of consul, but your team have already made a wrapper for consul's api, so I think this method is necessary!

It will be easy to implement, I saw there is a method called` GetServiceEndpoint(serviceID string) ` , which get register service by serviceId, just create a new method without that by serviceID parameter.

I can push my PR if your team think it's ok.

**Comment by lenny-intel** [comment]
@badboy-huaqiao , yes this seems useful. We will discuss at Core WG this week. @JamesKButcher one for this week's agenda.

**Comment by badboy-huaqiao** [comment]
@lenny-intel ok, it's better to force to add tags such as core, support, deviceservice, appservice when register service to consul to make it easier to classify.

**Comment by lenny-intel** [comment]
> it's better to force to add tags such as core, support, deviceservice, appservice when register service to consul to make it easier to classify.

@badboy-huaqiao , agreed this would help.
